### ISSUE TITLE
[Errno 2] No such file or directory: 'vim'

### ISSUE THREAD

**Issue by tkedwards** [kz6fittycent/jrnl-snap#1]
Thanks for making a Snap for jrnl, but unfortunately I can't get it to work:
```
$ jrnl --edit -on yesterday
Password: 
[Errno 2] No such file or directory: 'vim'

Please check the 'editor' key in your config file for errors:
    'vim'
```

.config/jrnl/jrnl.yaml
```
colors:
  body: none
  date: none
  tags: none
  title: none
default_hour: 9
default_minute: 0
editor: /usr/bin/vim
encrypt: true
highlight: true
indent_character: '|'
journals:
  default:
    encrypt: true
    journal: /home/someuser/jrnl/journal.txt
linewrap: 79
tagsymbols: '@'
template: false
timeformat: '%Y-%m-%d %H:%M'
version: v2.4.3

```
```
$ which vim
/usr/bin/vim
```
